//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LSOmni.DataAccess.BOConnection.PreCommon.OmniWrapper2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OmniWrapper2_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2")]
    public partial class OmniWrapper2 : MySoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDirectMarketingInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OmniWrapper2() {
            this.Url = global::LSOmni.DataAccess.BOConnection.PreCommon.Properties.Settings.Default.LSOmni_DataAccess_BOConnection_PreCommon_OmniWrapper2_OmniWrapper2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDirectMarketingInfoCompletedEventHandler GetDirectMarketingInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2:GetDirectMarketingInfo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", ResponseElementName="GetDirectMarketingInfo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDirectMarketingInfo(ref string responseCode, ref string errorText, string cardId, string itemNo, string storeNo, ref RootGetDirectMarketingInfo loadMemberDirMarkInfoXML) {
            object[] results = this.Invoke("GetDirectMarketingInfo", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        itemNo,
                        storeNo,
                        loadMemberDirMarkInfoXML});
            responseCode = ((string)(results[0]));
            errorText = ((string)(results[1]));
            loadMemberDirMarkInfoXML = ((RootGetDirectMarketingInfo)(results[2]));
        }
        
        /// <remarks/>
        public void GetDirectMarketingInfoAsync(string responseCode, string errorText, string cardId, string itemNo, string storeNo, RootGetDirectMarketingInfo loadMemberDirMarkInfoXML) {
            this.GetDirectMarketingInfoAsync(responseCode, errorText, cardId, itemNo, storeNo, loadMemberDirMarkInfoXML, null);
        }
        
        /// <remarks/>
        public void GetDirectMarketingInfoAsync(string responseCode, string errorText, string cardId, string itemNo, string storeNo, RootGetDirectMarketingInfo loadMemberDirMarkInfoXML, object userState) {
            if ((this.GetDirectMarketingInfoOperationCompleted == null)) {
                this.GetDirectMarketingInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectMarketingInfoOperationCompleted);
            }
            this.InvokeAsync("GetDirectMarketingInfo", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        itemNo,
                        storeNo,
                        loadMemberDirMarkInfoXML}, this.GetDirectMarketingInfoOperationCompleted, userState);
        }
        
        private void OnGetDirectMarketingInfoOperationCompleted(object arg) {
            if ((this.GetDirectMarketingInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectMarketingInfoCompleted(this, new GetDirectMarketingInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class RootGetDirectMarketingInfo {
        
        private PublishedOffer[] publishedOfferField;
        
        private PublishedOfferImages[] publishedOfferImagesField;
        
        private PublishedOfferDetailLine[] publishedOfferDetailLineField;
        
        private PublishedOfferDetailLineImages[] publishedOfferDetailLineImagesField;
        
        private MemberCouponBuffer[] memberCouponBufferField;
        
        private MemberNotification[] memberNotificationField;
        
        private MemberNotificationImages[] memberNotificationImagesField;
        
        private PublishedOfferLine[] publishedOfferLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOffer")]
        public PublishedOffer[] PublishedOffer {
            get {
                return this.publishedOfferField;
            }
            set {
                this.publishedOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferImages")]
        public PublishedOfferImages[] PublishedOfferImages {
            get {
                return this.publishedOfferImagesField;
            }
            set {
                this.publishedOfferImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferDetailLine")]
        public PublishedOfferDetailLine[] PublishedOfferDetailLine {
            get {
                return this.publishedOfferDetailLineField;
            }
            set {
                this.publishedOfferDetailLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferDetailLineImages")]
        public PublishedOfferDetailLineImages[] PublishedOfferDetailLineImages {
            get {
                return this.publishedOfferDetailLineImagesField;
            }
            set {
                this.publishedOfferDetailLineImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberCouponBuffer")]
        public MemberCouponBuffer[] MemberCouponBuffer {
            get {
                return this.memberCouponBufferField;
            }
            set {
                this.memberCouponBufferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberNotification")]
        public MemberNotification[] MemberNotification {
            get {
                return this.memberNotificationField;
            }
            set {
                this.memberNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberNotificationImages")]
        public MemberNotificationImages[] MemberNotificationImages {
            get {
                return this.memberNotificationImagesField;
            }
            set {
                this.memberNotificationImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferLine")]
        public PublishedOfferLine[] PublishedOfferLine {
            get {
                return this.publishedOfferLineField;
            }
            set {
                this.publishedOfferLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class PublishedOffer {
        
        private string noField;
        
        private string discountTypeField;
        
        private string discountNoField;
        
        private string descriptionField;
        
        private string offerCategoryField;
        
        private string primaryTextField;
        
        private string secondaryTextField;
        
        private System.DateTime endingDateField;
        
        public PublishedOffer() {
            this.endingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountNo {
            get {
                return this.discountNoField;
            }
            set {
                this.discountNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OfferCategory {
            get {
                return this.offerCategoryField;
            }
            set {
                this.offerCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryText {
            get {
                return this.primaryTextField;
            }
            set {
                this.primaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryText {
            get {
                return this.secondaryTextField;
            }
            set {
                this.secondaryTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime EndingDate {
            get {
                return this.endingDateField;
            }
            set {
                this.endingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class PublishedOfferLine {
        
        private string publishedOfferNoField;
        
        private string discountTypeField;
        
        private string discountNoField;
        
        private int discountLineNoField;
        
        private int discountLineTypeField;
        
        private string discountLineIdField;
        
        private string discountLineDescriptionField;
        
        private string variantTypeField;
        
        private string variantCodeField;
        
        private bool excludeField;
        
        private string unitOfMeasureField;
        
        private int tableNoField;
        
        public PublishedOfferLine() {
            this.discountLineNoField = 0;
            this.discountLineTypeField = 0;
            this.excludeField = false;
            this.tableNoField = 0;
        }
        
        /// <remarks/>
        public string PublishedOfferNo {
            get {
                return this.publishedOfferNoField;
            }
            set {
                this.publishedOfferNoField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountNo {
            get {
                return this.discountNoField;
            }
            set {
                this.discountNoField = value;
            }
        }
        
        /// <remarks/>
        public int DiscountLineNo {
            get {
                return this.discountLineNoField;
            }
            set {
                this.discountLineNoField = value;
            }
        }
        
        /// <remarks/>
        public int DiscountLineType {
            get {
                return this.discountLineTypeField;
            }
            set {
                this.discountLineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountLineId {
            get {
                return this.discountLineIdField;
            }
            set {
                this.discountLineIdField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountLineDescription {
            get {
                return this.discountLineDescriptionField;
            }
            set {
                this.discountLineDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string VariantType {
            get {
                return this.variantTypeField;
            }
            set {
                this.variantTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VariantCode {
            get {
                return this.variantCodeField;
            }
            set {
                this.variantCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Exclude {
            get {
                return this.excludeField;
            }
            set {
                this.excludeField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        public int TableNo {
            get {
                return this.tableNoField;
            }
            set {
                this.tableNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class MemberNotificationImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public MemberNotificationImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class MemberNotification {
        
        private string noField;
        
        private string contactNoField;
        
        private string primaryTextField;
        
        private string secondaryTextField;
        
        private string whenDisplayField;
        
        private System.DateTime validFromDateField;
        
        private System.DateTime validToDateField;
        
        private string memberAttributeField;
        
        private string memberAttributeValueField;
        
        private string webLinkField;
        
        private string eMailDisclaimerField;
        
        private bool personalizedEMailField;
        
        private bool sendHTMLField;
        
        public MemberNotification() {
            this.validFromDateField = new System.DateTime(0);
            this.validToDateField = new System.DateTime(0);
            this.personalizedEMailField = false;
            this.sendHTMLField = false;
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryText {
            get {
                return this.primaryTextField;
            }
            set {
                this.primaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryText {
            get {
                return this.secondaryTextField;
            }
            set {
                this.secondaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string WhenDisplay {
            get {
                return this.whenDisplayField;
            }
            set {
                this.whenDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime ValidFromDate {
            get {
                return this.validFromDateField;
            }
            set {
                this.validFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime ValidToDate {
            get {
                return this.validToDateField;
            }
            set {
                this.validToDateField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAttribute {
            get {
                return this.memberAttributeField;
            }
            set {
                this.memberAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAttributeValue {
            get {
                return this.memberAttributeValueField;
            }
            set {
                this.memberAttributeValueField = value;
            }
        }
        
        /// <remarks/>
        public string WebLink {
            get {
                return this.webLinkField;
            }
            set {
                this.webLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MailDisclaimer")]
        public string EMailDisclaimer {
            get {
                return this.eMailDisclaimerField;
            }
            set {
                this.eMailDisclaimerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonalizedE-Mail")]
        public bool PersonalizedEMail {
            get {
                return this.personalizedEMailField;
            }
            set {
                this.personalizedEMailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendHTML {
            get {
                return this.sendHTMLField;
            }
            set {
                this.sendHTMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class MemberCouponBuffer {
        
        private string couponCodeField;
        
        private string descriptionField;
        
        private string barcodeField;
        
        /// <remarks/>
        public string CouponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class PublishedOfferDetailLineImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public PublishedOfferDetailLineImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class PublishedOfferDetailLine {
        
        private string offerNoField;
        
        private int lineNoField;
        
        private string descriptionField;
        
        public PublishedOfferDetailLine() {
            this.lineNoField = 0;
        }
        
        /// <remarks/>
        public string OfferNo {
            get {
                return this.offerNoField;
            }
            set {
                this.offerNoField = value;
            }
        }
        
        /// <remarks/>
        public int LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class PublishedOfferImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public PublishedOfferImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetDirectMarketingInfoCompletedEventHandler(object sender, GetDirectMarketingInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectMarketingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectMarketingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RootGetDirectMarketingInfo loadMemberDirMarkInfoXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootGetDirectMarketingInfo)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591